### PR TITLE
Fixes #8 - add allow_blank affirmation modifier.

### LINKED ISSUE #8: Allow blank affiramation
A recent change now requires us to support blank strings.  We should add in an `allow_blank => true` affirmation.

### PR DESCRIPTION
**Pull request by knappe**

### CODE REVIEW

**Comment by semmons99** [comment]
You'll probably want to steal this definition of `blank?` too.

```ruby
def blank?(val)
  case val
  when String
    val !~ /[^[:space:]]/
  else
    val.respond_to?(:empty?) ? val.empty? : !val
  end
end
```

**Comment by semmons99** [comment]
@glanotte would you review and examine @knappe's concerns?

**Comment by knappe** [comment]
@semmons99 Mind taking a second look?  @glanotte and I were able to clean this up.

**Comment by semmons99** [comment]
:metal:

**Pull request merged**
